In [ ]:
##SUPPORT VECTOR REGRESSION IMPLEMENTATION
##DATESET->TIPS DATASET WHICH IS PRESENT IN SEABORN LIBRARY

In [2]:
import seaborn as sns
df=sns.load_dataset('tips')

In [ ]:
df.head()    #total bill is the dependent feature

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [ ]:
df['sex'].value_counts()   #sex,smoker,time->binary category->label encoding,day ->3 categories one hot encoding

sex
Male      157
Female     87
Name: count, dtype: int64

In [6]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:

##independent and dependent features
X=df[['tip', 'sex', 'smoker', 'day', 'time', 'size']]
y=df['total_bill']

In [8]:
#train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [9]:
X_train.head()

      tip     sex smoker   day    time  size
171  3.16    Male    Yes   Sat  Dinner     2
89   3.00    Male     No  Thur   Lunch     2
157  3.75  Female     No   Sun  Dinner     4
219  3.09  Female    Yes   Sat  Dinner     4
234  3.00    Male    Yes   Sat  Dinner     2

In [ ]:
##Feature Encoding(Label encoding and onehot encoding)

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
#3 encoders for 3 binary catregories
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()

In [12]:
import warnings
warnings.filterwarnings('ignore')
X_train['sex']=le1.fit_transform(X_train['sex'])
X_train['smoker']=le2.fit_transform(X_train['smoker'])
X_train['time']=le3.fit_transform(X_train['time'])

In [13]:
X_train.head()

      tip  sex  smoker   day  time  size
171  3.16    1       1   Sat     0     2
89   3.00    1       0  Thur     1     2
157  3.75    0       0   Sun     0     4
219  3.09    0       1   Sat     0     4
234  3.00    1       1   Sat     0     2

In [14]:
##same thing on test dataset
X_test['sex']=le1.fit_transform(X_test['sex'])
X_test['smoker']=le2.fit_transform(X_test['smoker'])
X_test['time']=le3.fit_transform(X_test['time'])

In [15]:
X_test.head()

      tip  sex  smoker  day  time  size
64   2.64    1       0  Sat     0     3
63   3.76    1       1  Sat     0     4
55   3.51    1       0  Sun     0     2
111  1.00    0       0  Sat     0     1
225  2.50    0       1  Fri     1     2

In [16]:
##one hot encoding---using Column transformer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [19]:
ct=ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop='first'),[3])],remainder='passthrough')

In [21]:

X_train=ct.fit_transform(X_train)

In [22]:
X_test=ct.fit_transform(X_test)

In [24]:
##SVR--SUPPORT VECTOR REGRESSION
from sklearn.svm import SVR
svr=SVR()

In [25]:
svr.fit(X_train,y_train)

SVR()

In [26]:
y_pred=svr.predict(X_test)

In [27]:
from sklearn.metrics import r2_score,mean_absolute_error
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.5706720478532027
3.4965418730363

In [ ]:
##do hyper parameter tuning on this